export const GET_ALL_POKEMONS_STARTED = "GET_ALL_POKEMONS_STARTED";

export const GET_ALL_POKEMONS_SUCCESS = "GET_ALL_POKEMONS_SUCCESS";

export const GET_ALL_POKEMONS_ERROR = "GET_ALL_POKEMONS_ERROR ";

export const GET_POKEMON_STARTED = "GET_POKEMON_STARTED";

export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";

export const GET_POKEMON_ERROR = "GET_POKEMON_ERROR";
